# Generated by Django 4.1.7 on 2023-03-05 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='date_publication',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
