# Generated by Django 4.1.7 on 2023-03-15 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0005_alter_advertisement_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='date_publication',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата публикации'),
        ),
    ]
